@startuml
client -> cas认证中心: http://cas.ctest.baijiahulian.com/cas/login?service=http://127.0.0.1:8080/tongbao/sales/tool/user/userLoginInfo?userId=rRJL0vB166l5mkJm
cas认证中心 -> tb_win_server: 回调http://127.0.0.1:8080/tongbao/sales/tool/user/userLoginInfo?userId=rRJL0vB166l5mkJm
tb_win_server -> cas认证中心: 拼装url模拟登陆
cas认证中心 -> tb_win_server: 登陆人信息
tb_win_server -> tb_win_server: redis缓存人员信息,1d过期
tb_win_server -> 鲁班尺: 通宝服务端上报人员信息至鲁班尺
client --> tb_win_server: queryUserInfo
client <-- tb_win_server: 缓存中获取并返回

@enduml